services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3334:3334"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env.development
    command: npx ts-node-dev src/index.ts
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3334/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        ENV_NAME: development
    ports:
      - "3333:80"
    depends_on:
      backend:
        condition: service_healthy
    env_file:
      - ./frontend/.env.development
    restart: always