version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3334:3334"
    volumes:
      - ./backend/db.json:/app/db.json
    env_file:
      - ./backend/.env.staging
    command: npm run start:staging
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3334/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      args:
        ENV_NAME: staging
    ports:
      - "3333:80"
    depends_on:
      backend:
        condition: service_healthy
    env_file:
      - ./frontend/.env.staging
    restart: always
