version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3334:3334"
    volumes:
      - ./backend/db.json:/app/db.json
    env_file:
      - ./backend/.env.staging
    command: npm run start:staging
    restart: always

  frontend:
    build:
      context: ./frontend
      args:
        ENV_NAME: staging
    ports:
      - "3333:80"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env.staging
    restart: always
