services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3334:3334"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env.development
    command: npx ts-node-dev src/index.ts
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        ENV_NAME: development
    ports:
      - "3333:80"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env.development
    restart: always